apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  capacity:
   storage: 512Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/Users/dloftu389/k8pv/"
  storageClassName: slow
